booleanChoices:
  --allow-H-rich-ECSN: true
  --allow-rlof-at-birth: true
  --allow-touching-at-birth: false
  --angular-momentum-conservation-during-circularisation: false
  --check-photon-tiring-limit: false
  --circularise-binary-during-mass-transfer: true
  --common-envelope-allow-immediate-RLOF-post-CE-survive: false
  --common-envelope-allow-main-sequence-survive: true
  --common-envelope-allow-radiative-envelope-survive: false
  --common-envelope-lambda-nanjing-enhanced: false
  --common-envelope-lambda-nanjing-interpolate-in-mass: false
  --common-envelope-lambda-nanjing-interpolate-in-metallicity: false
  --common-envelope-lambda-nanjing-use-rejuvenated-mass: false
  --debug-to-file: false
  --detailed-output: false
  --enable-warnings: false
  --errors-to-file: false
  --evolve-pulsars: false
  --evolve-unbound-systems: false
  --mass-transfer: true
  --pair-instability-supernovae: true
  --population-data-printing: false
  --print-bool-as-string: false
  --pulsational-pair-instability: true
  --quiet: false
  --retain-core-mass-during-caseA-mass-transfer: false
  --revised-energy-formalism-nandez-ivanova: false
  --rlof-printing: true
  --store-input-files: true
  --switch-log: false
  --use-mass-loss: true
listChoices:
  --debug-classes: []
  --log-classes: []
numericalChoices:
  --common-envelope-alpha: 10.0
  --common-envelope-alpha-thermal: 1.0
  --common-envelope-lambda: 0.1
  --common-envelope-lambda-multiplier: 1.0
  --common-envelope-mass-accretion-constant: 0
  --common-envelope-mass-accretion-max: 0.1
  --common-envelope-mass-accretion-min: 0.04
  --common-envelope-recombination-energy-density: 1.5E13
  --common-envelope-slope-kruckow: -0.83333333333
  --cool-wind-mass-loss-multiplier: 1.0
  --debug-level: 0
  --eccentricity: 0.0
  --eccentricity-max: 1.0
  --eccentricity-min: 0.0
  --eddington-accretion-factor: 1
  --fix-dimensionless-kick-magnitude: -1.0
  --fryer-22-fmix: 0.5
  --fryer-22-mcrit: 5.75
  --grid-lines-to-process: null
  --grid-start-line: 0
  --hdf5-buffer-size: 1
  --hdf5-chunk-size: 100000
  --initial-mass: null
  --initial-mass-1: null
  --initial-mass-2: null
  --initial-mass-max: 150.0
  --initial-mass-min: 5.0
  --initial-mass-power: 0.0
  --kick-direction-power: 0.0
  --kick-magnitude: null
  --kick-magnitude-1: null
  --kick-magnitude-2: null
  --kick-magnitude-max: -1.0
  --kick-magnitude-random: null
  --kick-magnitude-random-1: null
  --kick-magnitude-random-2: null
  --kick-magnitude-sigma-CCSN-BH: 265.0
  --kick-magnitude-sigma-CCSN-NS: 265.0
  --kick-magnitude-sigma-ECSN: 30.0
  --kick-magnitude-sigma-USSN: 30.0
  --kick-mean-anomaly-1: null
  --kick-mean-anomaly-2: null
  --kick-phi-1: null
  --kick-phi-2: null
  --kick-scaling-factor: 1.0
  --kick-theta-1: null
  --kick-theta-2: null
  --log-level: 0
  --luminous-blue-variable-multiplier: 1.5
  --mass-ratio: null
  --mass-ratio-max: 1.0
  --mass-ratio-min: 0.01
  --mass-transfer-fa: 0.5
  --mass-transfer-jloss: 1.0
  --mass-transfer-jloss-macleod-linear-fraction: 0.5
  --mass-transfer-thermal-limit-C: 10.0
  --maximum-evolution-time: 13700.0
  --maximum-mass-donor-nandez-ivanova: 2.0
  --maximum-neutron-star-mass: 2.5
  --maximum-number-timestep-iterations: 99999
  --mcbur1: 1.6
  --metallicity: null
  --metallicity-max: 0.03
  --metallicity-min: 0.0001
  --minimum-secondary-mass: 0.1
  --muller-mandel-kick-multiplier-BH: 200.0
  --muller-mandel-kick-multiplier-NS: 400.0
  --neutrino-mass-loss-BH-formation-value: 0.1
  --number-of-systems: 10
  --orbital-period: null
  --orbital-period-max: 1000
  --orbital-period-min: 1.1
  --overall-wind-mass-loss-multiplier: 1.0
  --pisn-lower-limit: 60.0
  --pisn-upper-limit: 135.0
  --ppi-lower-limit: 35.0
  --ppi-upper-limit: 60.0
  --pulsar-birth-magnetic-field-distribution-max: 13.0
  --pulsar-birth-magnetic-field-distribution-min: 11.0
  --pulsar-birth-spin-period-distribution-max: 100.0
  --pulsar-birth-spin-period-distribution-min: 10.0
  --pulsar-magnetic-field-decay-massscale: 0.025
  --pulsar-magnetic-field-decay-timescale: 1000.0
  --pulsar-minimum-magnetic-field: 8.0
  --random-seed: 0
  --rotational-frequency: 0.0
  --rotational-frequency-1: 0.0
  --rotational-frequency-2: 0.0
  --semi-major-axis: null
  --semi-major-axis-max: 1000.0
  --semi-major-axis-min: 0.01
  --timestep-multiplier: 1
  --wolf-rayet-multiplier: 1.0
  --zeta-adiabatic-arbitrary: 1.0E5
  --zeta-main-sequence: 2.0
  --zeta-radiative-envelope-giant: 6.5
stringChoices:
  --black-hole-kicks: FALLBACK
  --case-BB-stability-prescription: ALWAYS_STABLE
  --chemically-homogeneous-evolution: PESSIMISTIC
  --common-envelope-lambda-prescription: LAMBDA_NANJING
  --common-envelope-mass-accretion-prescription: ZERO
  --eccentricity-distribution: ZERO
  --envelope-state-prescription: LEGACY
  --fryer-supernova-engine: DELAYED
  --grid: null
  --initial-mass-function: KROUPA
  --kick-direction: ISOTROPIC
  --kick-magnitude-distribution: MAXWELLIAN
  --logfile-common-envelopes: null
  --logfile-definitions: null
  --logfile-detailed-output: null
  --logfile-double-compact-objects: null
  --logfile-name-prefix: null
  --logfile-pulsar-evolution: null
  --logfile-rlof-parameters: null
  --logfile-supernovae: null
  --logfile-switch-log: null
  --logfile-system-parameters: null
  --logfile-type: HDF5
  --luminous-blue-variable-prescription: HURLEY_ADD
  --mass-loss-prescription: VINK
  --mass-ratio-distribution: FLAT
  --mass-transfer-accretion-efficiency-prescription: FIXED
  --mass-transfer-angular-momentum-loss-prescription: ISOTROPIC
  --mass-transfer-rejuvenation-prescription: STARTRACK
  --mass-transfer-thermal-limit-accretor: CFACTOR
  --metallicity-distribution: LOGUNIFORM
  --mode: BSE
  --neutrino-mass-loss-BH-formation: FIXED_MASS
  --neutron-star-equation-of-state: SSE
  --notes: null
  --notes-hdrs: null
  --orbital-period-distribution: LOGUNIFORM
  --output-container: null
  --output-path: null
  --pulsar-birth-magnetic-field-distribution: ZERO
  --pulsar-birth-spin-period-distribution: ZERO
  --pulsational-pair-instability-prescription: MARCHANT
  --remnant-mass-prescription: FRYER2012
  --rotational-velocity-distribution: ZERO
  --semi-major-axis-distribution: FLATINLOG
  --stellar-zeta-prescription: SOBERMAN
